# This workflow will do a clean installation of node dependencies, cache/restore them, and build the source code to run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: Build
